### PR TITLE
Login hover

### PR DESCRIPTION
**Pull request by eatorres**
Ended up not using redux or redux forms. They seem to be better for changing stored data rather than logins (since we only need to verify).
I also didn't use the libraries I mentioned (react-popup and react-bootstrap). While they ease up the css they restrict UI customization, so it looks still ugly but we got more freedom.

### CODE REVIEW

**Comment by eslong** [comment]
I'd recommend adding hard-coded minimum widths to the box and the components to avoid this from happening (i.e. when not fullscreen). We can worry about full responsive later, but for now this should be an easy fix

capture

**Comment by eatorres** [comment]
https://github.com/eatorres/Mediate/issues/7

**Comment by eatorres** [comment]
image

**Comment by eatorres** [comment]
image

**Pull request merged**
